---
- sourceModel: despatchAdvice
  targetModel: process_shipment_container_remove
  modelMapping:
    segmentListMapping:
    - targetSegment: payload
      segmentListVariableMapping:
        # get the shipment which is having unique shipment and DA is having line action code not deleted
      - variableName: tms_shipment
        operation:
          - customFunction:
              functionName: get_unique_shipment
      - variableName: missing_container
        operation:
        - customFunction:
            functionName: get_containers_for_delete
            fields: global_variable.tms_shipment

      sourceSegment: global_variable.missing_container
      fieldMapping:
      - targetField: containerActionEnumVal
        default: "AT_DELETE"
      segmentListMapping:
      - targetSegment: container
        fieldMapping:
        - targetField: systemContainerID
          sourceField: deletedSystemContainerId
