---
- sourceModel: despatchAdvice
  targetModel: process_remove_shipment_from_load
  modelMapping:
    segmentListMapping:
    - targetSegment: removeFromPlannedLoadData
      segmentListVariableMapping:
      - variableName: shipment_data_look_up
        operation:
          - customFunction:
              functionName: get_unique_shipment_lookup_from_payload
      sourceSegment: shipment.data

      fieldVariableMapping:
        - variableName: current_da
          operation:
            - customFunction:
                functionName: get_data_from_lookup
                fields: [field: shipmentNumber, field: shipFromLocationCode, field: global_variable.shipment_data_look_up]
        - variableName: input_load_id
          variableValue: global_variable.current_da.despatchAdviceTransportInformation.transportLoadId
        - variableName: shipment_list
          operation:
            - customFunction:
                functionName: get_shipment_as_list
                fields: [field: shipmentLeg.systemShipmentLegID]

      fieldMapping:
        - targetField: systemLoadID
          sourceField: systemLoadID
          condition:
            - customFunction:
                functionName: check_new_and_old_load_id_not_same
                fields: [field: global_variable.input_load_id, field: systemLoadID]
        - targetField: systemShipmentLegID
          sourceField: global_variable.shipment_list
          condition:
            - customFunction:
                functionName: check_new_and_old_load_id_not_same
                fields: [field: global_variable.input_load_id, field: systemLoadID]


- sourceModel: despatchAdvice
  targetModel: process_add_shipment_to_planned_load
  modelMapping:
    segmentListMapping:
    - targetSegment: assignToPlannedLoadData
      segmentListVariableMapping:
      - variableName: shipment_data_look_up
        operation:
          - customFunction:
              functionName: get_unique_shipment_lookup_from_payload
      sourceSegment: shipment.data

      fieldVariableMapping:
        - variableName: current_da
          operation:
            - customFunction:
                functionName: get_data_from_lookup
                fields: [field: shipmentNumber, field: shipFromLocationCode, field: global_variable.shipment_data_look_up]
        - variableName: input_load_id
          variableValue: global_variable.current_da.despatchAdviceTransportInformation.transportLoadId
        - variableName: shipment_list
          operation:
            - customFunction:
                functionName: get_shipment_as_list
                fields: [field: shipmentLeg.systemShipmentLegID]

      fieldMapping:
        - targetField: systemLoadID
          sourceField: global_variable.input_load_id
          condition:
            - customFunction:
                functionName: check_new_and_old_load_id_not_same
                fields: [field: global_variable.input_load_id, field: systemLoadID]
        - targetField: systemShipmentLegID
          sourceField: global_variable.shipment_list
          condition:
            - customFunction:
                functionName: check_new_and_old_load_id_not_same
                fields: [field: global_variable.input_load_id, field: systemLoadID]



