---
- sourceModel: despatchAdvice
  targetModel: process_shipment_update
  modelMapping:
    segmentListMapping:
    - targetSegment: payload
      sourceSegment: shipment.data
      condition:
        - customFunction:
            functionName: check_shipment_operational_status
            fields: currentShipmentOperationalStatusEnumVal

      fieldVariableMapping:
      - variableName: current_shipment
        variableValue: current_payload
      - variableName: despatchAdviceLineItem
        operation:
        - customFunction:
            functionName: get_unique_containers
            fields: shipmentNumber

      fieldMapping:
      - targetField: systemShipmentID
        sourceField: shipmentNumber
        condition:
        - customFunction:
            functionName: not_blank
            fields: global_variable.despatchAdviceLineItem
      - targetField: containerActionEnumVal
        operations:
          - customFunction:
              functionName: get_container_action_val
              fields: global_variable.despatchAdviceLineItem

      segmentListMapping:
      - targetSegment: container
        sourceSegment: global_variable.despatchAdviceLineItem
        fieldVariableMapping:
          -  variableName: adviceLineItemNumber
             variableValue: lineItem.transactionalReference.lineItemNumber
          -  variableName: shipmentMode
             variableValue: global_variable.current_shipment.shipmentEntryModeEnumVal
          -  variableName: adviceOrderNumber
             variableValue: lineItem.transactionalReference.entityId
          -  variableName: inputQty
             variableValue: lineItem.despatchedQuantity.value
          -  variableName: inputWeightType
             variableValue: lineItem.transactionalTradeItem.transactionalItemData.transactionalItemWeight.measurementType
          -  variableName: measurementUnitCode
             variableValue: lineItem.transactionalTradeItem.transactionalItemData.transactionalItemWeight.measurementValue.measurementUnitCode
          -  variableName: inputVolumeType
             variableValue: lineItem.avpList.name
          -  variableName: grossVolMeasurementUnitCode
             variableValue: lineItem.totalGrossVolume.measurementUnitCode
          -  variableName: unitVolMeasurementUnitCode
             variableValue: lineItem.avpList.qualifierCodeName
          -  variableName: shipmentContainerDocument
             operation:
               - customFunction:
                   functionName: get_shipment_container_document
                   # get this with the current iteration
                   fields: [field: global_variable.current_shipment, field: global_variable.adviceLineItemNumber]

          -  variableName: aggregatedLinesDoc
             operation:
               - customFunction:
                   functionName: get_aggregated_Lines
                   # get this with the current iteration
                   fields: [field: global_variable.current_shipment, field: global_variable.current_shipment.shipmentNumber, field: global_variable.adviceOrderNumber, field: global_variable.adviceLineItemNumber]

          - variableName: aggregatedQuantity
            operation:
            - customFunction:
                functionName: get_aggregated_qty_sum
                # get this with the current iteration
                fields: global_variable.aggregatedLinesDoc

          - variableName: aggregatedInputWeightValue
            operation:
            - customFunction:
                functionName: get_aggregated_unit_weight
                # get this with the current iteration
                fields: global_variable.aggregatedLinesDoc

          - variableName: aggregatedInputUnitNetVolume
            operation:
            - customFunction:
                functionName: get_aggregated_unit_net_volume
                # get this with the current iteration
                fields: global_variable.aggregatedLinesDoc

          - variableName: aggregatedInputTotalGrossVolume
            operation:
            - customFunction:
                functionName: get_aggregated_total_volume
                # get this with the current iteration
                fields: global_variable.aggregatedLinesDoc

          - variableName: totalWeightOfContainer
            operation:
            - customFunction:
                functionName: get_total_weight_of_container
                # get this with the current iteration
                fields: [field: global_variable.inputWeightType,field: global_variable.aggregatedInputWeightValue,field: global_variable.measurementUnitCode, field: global_variable.aggregatedQuantity, property: tms.uom.weight]

          - variableName: inputUnitWeight
            operation:
            - customFunction:
                functionName: get_input_weight
                # get this with the current iteration
                fields: [field: global_variable.inputWeightType, field: global_variable.aggregatedInputWeightValue, field: global_variable.measurementUnitCode, field: global_variable.aggregatedQuantity, field: global_variable.totalWeightOfContainer, property: tms.uom.weight]


          - variableName: totalVolumeOfContainer
            operation:
            - customFunction:
                functionName: get_total_volume_of_container
                # get this with the current iteration
                fields: [field: global_variable.inputVolumeType, field: global_variable.aggregatedInputTotalGrossVolume, field: global_variable.grossVolMeasurementUnitCode, field: global_variable.unitVolMeasurementUnitCode, field: global_variable.aggregatedQuantity, property: tms.uom.volume]

          - variableName: containerUnitVolume
            operation:
            - customFunction:
                functionName: get_container_unit_volume
                # get this with the current iteration
                fields: [field: global_variable.inputVolumeType, field: global_variable.aggregatedInputTotalGrossVolume, field: global_variable.grossVolMeasurementUnitCode, field: global_variable.aggregatedQuantity, field: global_variable.totalVolumeOfContainer, property: tms.uom.volume]

        addData:
          - customFunction:
              functionName: remove_field_from_payload
              # get this with the current iteration
              fields: [field: global_variable.shipmentContainerDocument, constant: "containerShippingInformation",constant: "quantity",constant: "numberOfUnits",constant: "weightByFreightClass",constant: "transportOrderInfo"]

          - customFunction:
              functionName: add_shipment_mode
              # get this with the current iteration
              fields: [field: global_variable.shipmentContainerDocument, field: global_variable.shipmentMode]

        fieldMapping:
          - targetField: quantity
            condition:
              - customFunction:
                  functionName: check_override_planned_true
                  fields: [field: global_variable.shipmentContainerDocument, property: override.planned.estimate]
            sourceField: global_variable.aggregatedQuantity
          - targetField: quantity
            condition:
              - customFunction:
                  functionName: check_override_planned_false
                  fields: [field: global_variable.shipmentContainerDocument, property: override.planned.estimate]
            sourceField: global_variable.shipmentContainerDocument.quantity

        segmentMapping:
        - targetSegment: containerShippingInformation
          condition:
            - customFunction:
                functionName: check_shipment_document
                fields: global_variable.shipmentContainerDocument

          addData:
            - customFunction:
                functionName: remove_field_from_payload
                # get this with the current iteration
                fields: [field: global_variable.shipmentContainerDocument.containerShippingInformation, constant: "nominalWeight", constant: "volume"]
          fieldMapping:
          - targetField: volume
            sourceField: global_variable.containerUnitVolume
          - targetField: nominalWeight
            sourceField: global_variable.inputUnitWeight
        segmentListMapping:
        - targetSegment: weightByFreightClass
          condition:
            - customFunction:
                functionName: check_shipment_document
                fields: [field: global_variable.shipmentContainerDocument]
          fieldMapping:
            - targetField: freightClassCode
              sourceField: global_variable.shipmentContainerDocument.weightByFreightClass[0].freightClassCode
            - targetField: freightClassNominalWeight
              condition:
                - customFunction:
                    functionName: check_override_planned_true
                    fields: [field: global_variable.shipmentContainerDocument, property: override.planned.estimate]
              sourceField: global_variable.inputUnitWeight
            - targetField: freightClassNominalWeight
              condition:
                - customFunction:
                    functionName: check_override_planned_false
                    fields: [field: global_variable.shipmentContainerDocument, property: override.planned.estimate]
              sourceField: global_variable.shipmentContainerDocument.weightByFreightClass[0].freightClassNominalWeight
