- sourceModel: despatchAdvice
  targetModel: process_reference_number_update
  modelMapping:
    segmentListMapping:
    - targetSegment: payload
      segmentListVariableMapping:
      - variableName: unique_load_despact_advice
        operation:
          - customFunction:
              functionName: get_unique_load_despatch_advice
      sourceSegment: global_variable.unique_load_despact_advice
      fieldVariableMapping:
      - variableName: current_da
        # keep track of the curr da Details
        variableValue: current_payload
      - variableName: loadDocument
        operation:
          - customFunction:
              functionName: get_current_load
              fields: despatchAdviceTransportInformation.transportLoadId
      - variableName: shippingLocationCode
        variableValue: shipFrom.primaryId
      - variableName: loadReferenceNumberID
        operation:
          - customFunction:
              functionName: get_load_reference_id
              fields: global_variable.loadDocument
      - variableName: stopStatus
        operation:
          - customFunction:
              functionName: get_stop_status
              fields: [field: global_variable.shippingLocationCode, constant: "-SHIPPED"]
      - variableName: stopDocument
        operation:
          - customFunction:
              functionName: get_stop_document
              fields: [field: global_variable.loadDocument, field: global_variable.shippingLocationCode]
      - variableName: loadStatus
        operation:
          - customFunction:
              functionName: get_load_status
              fields: [field: global_variable.loadDocument, field: global_variable.shippingLocationCode, field: global_variable.stopStatus]
      - variableName: systemStopID
        variableValue: global_variable.stopDocument.systemStopID
      - variableName: stopReferenceNumberID
        operation:
          - customFunction:
              functionName: get_stop_reference_number
              fields: global_variable.stopDocument
      - variableName: referenceNumberActionEnumVal
        operation:
          - customFunction:
              functionName: get_tm_property
              fields: [property: tms.refNumActionEnumVal.update]

      segmentListMapping:
        - targetSegment: referenceNumberUpdateData
          condition:
          - customFunction:
              functionName: check_condition_for_load_ref_update
              fields: [field: global_variable.referenceNumberActionEnumVal, field: global_variable.loadDocument.systemLoadID, field: global_variable.loadReferenceNumberID]
          fieldMapping:
          - targetField:  referenceNumberTypeCode
            default: WM_WH_STS_
          - targetField:  referenceNumberEntityKey
            sourceField: global_variable.loadDocument.systemLoadID
          - targetField:  referenceNumberCategoryEnumVal
            default: RNC_LD_LEG
          - targetField:  referenceNumber
            sourceField: global_variable.loadStatus
          addData:
            - customFunction:
                functionName: get_reference_number_action_enum_val
                # get this with the current iteration
                fields: [field: global_variable.referenceNumberActionEnumVal, field: global_variable.loadReferenceNumberID]


        - targetSegment: referenceNumberUpdateData
          condition:
            - customFunction:
                functionName: check_condition_for_stop_ref_update
                fields: [field: global_variable.referenceNumberActionEnumVal, field: global_variable.systemStopID, field: global_variable.stopReferenceNumberID ]
          fieldMapping:
          - targetField:  referenceNumberTypeCode
            default: WM_SHP_STS
          - targetField:  referenceNumberEntityKey
            sourceField: global_variable.loadDocument.systemStopID
          - targetField:  referenceNumberCategoryEnumVal
            default: RNC_STOP
          - targetField:  referenceNumber
            sourceField: global_variable.stopStatus
          addData:
            - customFunction:
                functionName: get_reference_number_action_enum_val
                # get this with the current iteration
                fields: [field: global_variable.referenceNumberActionEnumVal, field: global_variable.stopReferenceNumberID]

        - targetSegment: referenceNumberUpdateData
          condition:
            - customFunction:
                functionName: check_condition_for_bol_ref_update
                fields: [field: global_variable.stopDocument, field: global_variable.current_da]

          fieldMapping:
          - targetField:  referenceNumberTypeCode
            default: OL
          - targetField:  referenceNumberEntityKey
            sourceField: global_variable.systemStopID
          - targetField:  referenceNumberCategoryEnumVal
            default: RNC_STOP
          - targetField:  referenceNumber
            sourceField: global_variable.current_da.dropOffStop.billOfLadingNumber.entityId
          - targetField:  referenceNumberActionEnumVal
            default: AT_ADD