- sourceModel: despatchAdvice
  targetModel: process_load_update
  modelMapping:
    segmentListMapping:
    - targetSegment: payload
      segmentListMapping:
      - targetSegment: loadUpdateData
        segmentListVariableMapping:
          - variableName: despatch_advice_with_srn
            operation:
              - customFunction:
                  functionName: get_despatch_advice_with_srn
        sourceSegment: global_variable.despatch_advice_with_srn
        fieldVariableMapping:
        - variableName: current_da
          # keep track of the curr da Details
          variableValue: current_payload
        - variableName: loadDocument
          operation:
          - customFunction:
              functionName: get_current_load
              # get this with the current iteration
              fields: despatchAdviceTransportInformation.transportLoadId

        fieldMapping:
        - targetField:  systemLoadID
          sourceField: global_variable.loadDocument.systemLoadID
        - targetField:  loadDescription
          operations:
            - customFunction:
                functionName: get_load_description
                # get this with the current iteration
                fields: [field: global_variable.loadDocument, field: global_variable.current_da]
        - targetField:  trailerLicenseNumber
          operations:
            - customFunction:
                functionName: get_trailer_license_number
                # get this with the current iteration
                fields: [field: global_variable.current_da]
        - targetField:  tractorLicenseNumber
          operations:
            - customFunction:
                functionName: get_tractor_license_number
                # get this with the current iteration
                fields: [field: global_variable.current_da]
        - targetField:  driverLicenseNumber
          operations:
            - customFunction:
                functionName: get_driver_license_number
                # get this with the current iteration
                fields: [field: global_variable.current_da]