triggers:

# Entity Enrichment Config - START
  item:
    options:
      enricher_enabled: true
      enriched_payload_enabled: false

  transportPickUpDropOffRequest:
    options:
      enricher_enabled: true
      enriched_payload_enabled: true

  apVoucher:
    options:
      enricher_enabled: true
      enriched_payload_enabled: false

  arVoucher:
    options:
      enricher_enabled: true
      enriched_payload_enabled: false

  transportLoad:
    options:
      enricher_enabled: true
      enriched_payload_enabled: false

  orderRelease:
    options:
      enricher_enabled: true
      enricher_mode: parallel

  despatchAdvice:
    options:
      enricher_enabled: true
      enriched_payload_enabled: false
      #required for http enricher
      enriched_data_segment: shipment
      function: "http_enricher"
      function_args: ["", ""]

  receivingAdvice:
    options:
      enricher_enabled: true
      enriched_payload_enabled: false
      #required for http enricher
      enriched_data_segment: shipment

  transportPickUpDropOffConfirmation:
    options:
      enricher_enabled: true
      enriched_payload_enabled: true

  warehousingOutboundNotification:
    options:
      enricher_enabled: true
      enriched_payload_enabled: true

  warehousingOutboundInstruction:
    options:
      enricher_enabled: true
      enriched_payload_enabled: false


# Entity Enrichment Config - END

# Trigger Config - START

  aeh_tms_listener:
    connection:
      event_hub_name: "neo-tma-evh"
      connection_string: "keyvault::{ENVIRONMENT}-{REALM}-tma-aeh-topic"
      group_id: "$Default"
    options:
      storage_connection_string: "keyvault::{ENVIRONMENT}-{REALM}-storage-connection"
      checkpoint_container_name: neo-checkpoint

  dockCommitmentCreated:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_DockCommitmentCreated"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  dockCommitmentChanged:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_DockCommitmentChanged"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  dockCommitmentDeleted:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_DockCommitmentDeleted"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  LoadTenderAcceptedListener_jms:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_LoadTenderAccepted"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  LoadTenderCancelledListener_jms:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_LoadTenderCancelled"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  LoadTenderUpdatedListener_jms:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_LoadTenderUpdated"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  LoadStopAppointmentListener_jms:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_LoadStopAppointment"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  ShipmentLegAddedToPlannedLoad_jms:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_ShipmentLegAddedToPlannedLoad"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  ShipmentLegRemovedFromLoad_jms:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_ShipmentLegRemovedFromLoad"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  LoadRoutedRatedScheduledListener_jms:
    type: "jms"
    connection:
      username: "keyvault::{ENVIRONMENT}-{REALM}-jms-username"
      password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-password"
      host: "localhost"
      port: "61613"
      default_queue_name: "TM_NEN_LoadRoutedRatedScheduled"
      consumer_count: "1"
      connection_retry_count: "20"
      prefetch_count: "50"
      failover_enabled: true
      failover:
        host: "localhost"
        port: "61613"
        username: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-username"
        password-secure: "keyvault::{ENVIRONMENT}-{REALM}-jms-failover-password"

  inbound_claim_check_blob:
    retries: 10
    retry_sleep: 5
    connectionString: keyvault::{ENVIRONMENT}-{REALM}-storage-connection

  inbound_tracking_claim_check_blob:
    retries: 10
    retry_sleep: 5
    connectionString: keyvault::{ENVIRONMENT}-{REALM}-storage-connection

  apVoucher_scheduler:
    type: "scheduler"
    options:
      scheduler_type: "inbound_claim_check_blob"
      function: "azure_blob_read"
      frequency: "Daily"
      time: "12:48"
      #scheduler_trigger_transform: "transformations/tms/inbound/apvoucher/neo_native_notification_format.yaml"

  arVoucher_scheduler:
    type: "scheduler"
    options:
      scheduler_type: "inbound_claim_check_blob"
      function: "azure_blob_read"
      frequency: "Daily"
      time: "12:48"
      #scheduler_trigger_transform: "transformations/tms/inbound/apvoucher/neo_native_notification_format.yaml"
# Trigger Config - END