---
- sourceModel: warehousingOutboundNotification
  targetModel: update_shipment_detail
  modelMapping:
    segmentListMapping:
      - targetSegment: payload
        # variables
        fieldVariableMapping:
          - variableName: shipment_to_containers
            operation:
              - customFunction:
                  functionName: map_shipment_to_won_containers
                  fields: [shipment]

        # transformation
        fieldMapping:
          - targetField: ignoreAllReferenceNumbersFlag
            default: false
          - targetField: containerActionEnumVal
            default: AT_UPDATE
        segmentListMapping:
          - targetSegment: container
            sourceSegment: global_variable.shipment_to_containers
            segmentMapping:
              - targetSegment: containerShippingInformation
                fieldMapping:
                  - targetField: scaledWeight
                    sourceField: mapped_data.scaledWeight
                  - targetField: orderValue
                    sourceField: mapped_data.orderValue
                  - targetField: declaredValue
                    sourceField: mapped_data.declaredValue
                  - targetField: tareWeight
                    sourceField: mapped_data.tareWeight
                  - targetField: pieces
                    sourceField: mapped_data.pieces
                  - targetField: skids
                    sourceField: mapped_data.skids
                  - targetField: ladenLength
                    sourceField: mapped_data.ladenLength
                  - targetField: volume
                    sourceField: mapped_data.volume
                  - targetField: nominalWeight
                    sourceField: mapped_data.input_unit_weight

            segmentListMapping:
            - targetSegment: weightByFreightClass
              fieldMapping:
              - targetField: freightClassCode
                sourceField: mapped_data.freightClassCode
              - targetField: freightClassNominalWeight
                sourceField: mapped_data.input_unit_weight
            fieldMapping:
              - targetField: quantity
                sourceField: mapped_data.input_qty
              - targetField: numberOfUnits
                sourceField: mapped_data.numberOfUnits
              - targetField: ignoreShipmentItemsFlag
                condition:
                  options:
                    - customFunction:
                        functionName: is_ild_summary_mandatory
                        fields: [shipment]
                default: true
              - targetField: ignoreWeightByFreightClassFlag
                condition:
                  options:
                    - customFunction:
                        functionName: is_ild_summary_mandatory
                        fields: [shipment]
                default: false
            injectPayload:
            - customFunction:
                functionName: remove_field_from_payload_with_nested_namespace
                fields: [field: mapped_data.original_data, constant: "containerShippingInformation",constant: "quantity",constant: "numberOfUnits",constant: "weightByFreightClass",constant: "transportOrderInfo"]

- sourceModel: warehousingOutboundNotification
  targetModel: update_reference_numbers
  modelMapping:
    segmentListMapping:
      - targetSegment: payload
        # variables
        fieldVariableMapping:
          - variableName: input_payload
            variableValue: current_payload
          - variableName: WON_ShippingLocationCode
            variableValue: global_variable.input_payload.warehousingOutboundNotification.shipment.shipFrom.primaryId
          - variableName: shipments
            operation:
              - customFunction:
                  functionName: map_shipment_to_reference_numbers
                  fields: [global_variable.input_payload.shipment]
          - variableName: loadReferenceNumberID
            operation:
              - customFunction:
                  functionName: get_load_reference_number_id_won
                  fields: [field: global_variable.input_payload.load ]
        segmentListMapping:
          - targetSegment: referenceNumberUpdateData
            sourceSegment: global_variable.shipments
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: WM_SHIPMENT
              - targetField: referenceNumberEntityKey
                sourceField: mapped_data.reference_number_entity_key
              - targetField: referenceNumberCategoryEnumVal
                default: RNC_SHPM
              - targetField: systemReferenceNumberID
                sourceField: mapped_data.system_reference_number_id
              - targetField: referenceNumber
                sourceField: mapped_data.reference_number
              - targetField: referenceNumberActionEnumVal
                sourceField: mapped_data.reference_number_action_enum_val

          - targetSegment: referenceNumberUpdateData
            condition:
              customFunction:
                functionName: check_valid_reference_number_update_for_won_load
                fields: [ field: shipment.shipmentTransportationInformation.transportLoadId, field: global_variable.input_payload.load.systemLoadID, field: global_variable.loadReferenceNumberID]
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: "WM_WH_STS_"
              - targetField: referenceNumberEntityKey
                sourceField: input_payload.load.systemLoadID
              - targetField: referenceNumberCategoryEnumVal
                default: "RNC_LD_LEG"
              - targetField: referenceNumber
                operations:
                  - customFunction:
                      functionName: get_reference_number_for_load_won
                      fields: [ field: global_variable.input_payload.load.stop, field: global_variable.WON_ShippingLocationCode ]
              - targetField: referenceNumberActionEnumVal
                operations:
                  - customFunction:
                      functionName: get_reference_number_action_enum_for_stop_won
                      fields: [ field: global_variable.loadReferenceNumberID]
              - targetField: SystemReferenceNumberID
                sourceField: global_variable.loadReferenceNumberID

          - targetSegment: referenceNumberUpdateData
            sourceSegment: global_variable.input_payload.load.stop
            condition:
              customFunction:
                functionName: check_valid_reference_number_update_for_won_stop
                fields: [
                    field: global_variable.input_payload.shipment.shipmentTransportationInformation.transportLoadId,
                    field: global_variable.input_payload.load.systemLoadID,
                    field: SystemStopID,
                    field: stopReferenceNumberID
                ]
            fieldVariableMapping:
            - variableName: stopReferenceNumberID
              operation:
                - customFunction:
                    functionName: get_stop_reference_number_id_won
                    fields: [
                        field: referenceNumberStructure,
                        field: ShippingLocationCode,
                        field: WON_ShippingLocationCode
                    ]
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: "WM_SHP_STS"
              - targetField: referenceNumberEntityKey
                sourceField: systemStopID
              - targetField: referenceNumberCategoryEnumVal
                default: "RNC_STOP"
              - targetField: referenceNumber
                operations:
                  - customFunction:
                      functionName: get_reference_number_for_stop_won
                      fields: [ field: global_variable.WON_ShippingLocationCode]
              - targetField: referenceNumberActionEnumVal
                operations:
                  - customFunction:
                      functionName: get_reference_number_action_enum_for_stop_won
                      fields: [ field: global_variable.stopReferenceNumberID ]
              - targetField: SystemReferenceNumberID
                sourceField: global_variable.stopReferenceNumberID


- sourceModel: warehousingOutboundNotification
  targetModel: update_stop_planning_status
  sourceCondition:
    customFunction:
      functionName: check_if_stop_planning_status
      functionArgs: [ property: 'updateStopPlanningStatus' ]
  modelMapping:
    segmentListMapping:
      - targetSegment: payload
        fieldVariableMapping:
          - variableName: stop_planning_status_enum_val
            operation:
              - customFunction:
                  functionName: map_load_to_stop_planning_status_enum_val
                  fields: [load]

        segmentListMapping:
          - targetSegment: stopUpdateData
            sourceSegment: warehousingOutboundNotification.shipment
            fieldMapping:
              - targetField: systemLoadID
                sourceField: shipmentTransportationInformation.transportLoadId
              - targetField: shippingLocationCode
                sourceField: shipFrom.primaryId
              - targetField: stopPlanningStatusEnumVal
                sourceField: global_variable.stop_planning_status_enum_val
              - targetField: IgnoreReferenceNumbersFlag
                default: 'true'

- sourceModel: warehousingOutboundNotification
  targetModel: update_load_planning_status
  sourceCondition:
    customFunction:
      functionName: check_if_load_planning_status
      functionArgs: [ property: 'updateStopPlanningStatus' ]
  modelMapping:
    segmentListMapping:
      - targetSegment: payload
        fieldVariableMapping:
          - variableName: load_planning_status_enum_val
            operation:
              - customFunction:
                  functionName: evaluate_load_planning_status_enum_val
                  fields: [
                      field: load,
                      field: warehousingOutboundNotification.shipment.warehousingOutboundStatusCode
                  ]
        segmentListMapping:
          - targetSegment: loadUpdateData
            sourceSegment: warehousingOutboundNotification.shipment
            fieldMapping:
              - targetField: systemLoadID
                sourceField: shipmentTransportationInformation.transportLoadId
              - targetField: planningStatusEnumVal
                sourceField: global_variable.load_planning_status_enum_val
