---
- sourceModel: warehousingOutboundNotification
  targetModel: update_shipment_detail
  modelMapping:
    segmentListMapping:
      - targetSegment: payload
        # variables
        fieldVariableMapping:
          - variableName: shipment_to_containers
            operation:
              - customFunction:
                  functionName: map_shipment_to_won_containers
                  fields: [shipment]

        # transformation
        fieldMapping:
          - targetField: ignoreAllReferenceNumbersFlag
            default: false
        segmentListMapping:
          - targetSegment: container
            sourceSegment: global_variable.shipment_to_containers
            segmentMapping:
              - targetSegment: containerShippingInformation
                fieldMapping:
                  - targetField: scaledWeight
                    sourceField: mapped_data.scaledWeight
                  - targetField: orderValue
                    sourceField: mapped_data.orderValue
                  - targetField: declaredValue
                    sourceField: mapped_data.declaredValue
                  - targetField: tareWeight
                    sourceField: mapped_data.tareWeight
                  - targetField: pieces
                    sourceField: mapped_data.pieces
                  - targetField: skids
                    sourceField: mapped_data.skids
                  - targetField: ladenLength
                    sourceField: mapped_data.ladenLength
                  - targetField: volume
                    sourceField: mapped_data.volume
                  - targetField: nominalWeight
                    sourceField: mapped_data.input_unit_weight
              - targetSegment: weightByFreightClass
                fieldMapping:
                  - targetField: freightClassCode
                    sourceField: mapped_data.freightClassCode
                  - targetField: freightClassNominalWeight
                    sourceField: mapped_data.input_unit_weight
            fieldMapping:
              - targetField: quantity
                sourceField: mapped_data.input_qty
              - targetField: numberOfUnits
                sourceField: mapped_data.numberOfUnits
              - targetField: ignoreShipmentItemsFlag
                condition:
                  options:
                    - customFunction:
                        functionName: is_ild_summary_mandatory
                        fields: [shipment]
                default: true
              - targetField: ignoreWeightByFreightClassFlag
                condition:
                  options:
                    - customFunction:
                        functionName: is_ild_summary_mandatory
                        fields: [shipment]
                default: false
            injectPayload:
            - customFunction:
                functionName: remove_field_from_payload_with_nested_namespace
                fields: [field: mapped_data.original_data, constant: "containerShippingInformation",constant: "quantity",constant: "numberOfUnits",constant: "weightByFreightClass",constant: "transportOrderInfo"]