---
- sourceModel: warehousingOutboundNotification
  targetModel: update_reference_numbers
  modelMapping:
    segmentListMapping:
      - targetSegment: payload
        # variables
        fieldVariableMapping:
          - variableName: shipments
            operation:
              - customFunction:
                  functionName: map_shipment_to_reference_numbers
                  fields: [shipment]
        segmentListMapping:
          - targetSegment: referenceNumberUpdateData
            sourceSegment: global_variable.shipments
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: WM_SHIPMENT
              - targetField: referenceNumberEntityKey
                sourceField: mapped_data.reference_number_entity_key
              - targetField: referenceNumberCategoryEnumVal
                default: RNC_SHPM
              - targetField: systemReferenceNumberID
                sourceField: mapped_data.system_reference_number_id
              - targetField: referenceNumber
                sourceField: mapped_data.reference_number
              - targetField: referenceNumberActionEnumVal
                sourceField: mapped_data.reference_number_action_enum_val
