---
- sourceModel: orderRelease
  targetModel: process_shipment_delete
  sourceCondition:
    customFunction:
      functionName: check_document_action_code_order_delete_from_wms
      functionArgs: [field: orderRelease, field: enrichment.shipment]
  modelMapping:
    fieldVariableMapping:
      - variableName: enrichment
        variableValue: enrichment
    segmentListMapping:
      - targetSegment: shipment
        sourceSegment: orderRelease
        fieldMapping:
          - targetField: shipmentNumber
            sourceField: global_variable.enrichment.shipment.shipmentNumber

