---
- sourceModel: orderRelease
  targetModel: process_shipment_update
  sourceCondition:
    customFunction:
      functionName: check_document_action_code_orderLine_delete_from_wms
      functionArgs: [field: orderRelease, field: enrichment.shipment]
  modelMapping:
    fieldVariableMapping:
      - variableName: enrichment
        variableValue: enrichment
      - variableName : orderMessage
        variableValue: orderRelease
    fieldMapping:
      - targetField: containerActionEnumVal
        default: AT_DELETE
    segmentListMapping:
      - targetSegment: container
        sourceSegment: orderRelease
        fieldVariableMapping:
          - variableName: system_container_id
            operations:
              - customFunction:
                  functionName: get_container_id_for_order_line_delete
                  fields: [ field: global_variable.orderMessage, field: global_variable.enrichment.shipment ]
        fieldMapping:
          - targetField: systemContainerID
            sourceField: global_variable.system_container_id