---
- sourceModel: orderRelease
  targetModel: process_remove_shipment_from_planned_load
  sourceCondition:
    customFunction:
      functionName: check_document_action_code_cancel
      functionArgs: [field: orderRelease, field: enrichment.shipment]
  modelMapping:
    fieldVariableMapping:
      - variableName: enrichment
        variableValue: enrichment
      - variableName: remove_shipment_list
        operations:
          - customFunction:
              functionName: get_remove_shipment_details
              fields: [ field: orderRelease, field: global_variable.enrichment.shipment ]

    segmentListMapping:
      - targetSegment: removeFromPlannedLoadData
        fieldMapping:
          - targetField: systemLoadID
            sourceField: global_variable.enrichment.shipment.shipmentLeg.systemLoadID
            condition:
              - customFunction:
                  functionName: check_load_status_and_load_id
                  fields: [ field: global_variable.enrichment.shipment.shipmentLeg.load.currentLoadOperationalStatusEnumVal]
          - targetField: systemShipmentLegID
            sourceField: global_variable.remove_shipment_list
            condition:
              - customFunction:
                  functionName: check_load_status_and_load_id
                  fields: [ field: global_variable.enrichment.shipment.shipmentLeg.load.currentLoadOperationalStatusEnumVal ]


- sourceModel: orderRelease
  targetModel: process_shipment_cancel
  sourceCondition:
    customFunction:
      functionName: check_document_action_code_cancel
      functionArgs: [field: orderRelease, field: enrichment.shipment]
  modelMapping:
    fieldVariableMapping:
      - variableName: enrichment
        variableValue: enrichment
    fieldMapping:
      - targetField: shipmentIDType
        default: SI_NUM
    segmentListMapping:
      - targetSegment: shipment
        sourceSegment: orderRelease
        fieldVariableMapping:
          - variableName: shipment_enrichment
            operations:
              - customFunction:
                  functionName: get_shipment_details
                  fields: [ field: orderId, field: global_variable.enrichment.shipment ]
        fieldMapping:
          - targetField: shipmentNumber
            sourceField: global_variable.shipment_enrichment.shipmentNumber

