---
- sourceModel: orderRelease
  targetModel: process_shipment_cancel
  sourceCondition:
    customFunction:
      functionName: check_document_action_code_order_cancel_from_wms
      functionArgs: [field: orderRelease, field: enrichment.shipment]
  modelMapping:
    fieldVariableMapping:
      - variableName: enrichment
        variableValue: enrichment
    fieldMapping:
      - targetField: shipmentIDType
        default: SI_NUM
      - targetField: shipment
        operations:
          - customFunction:
              functionName: get_shipment_details_for_wms_host
              fields:  global_variable.enrichment.shipment


