---
- sourceModel: warehousingOutboundNotification
  targetModel: process_product_picked_item_update
  sourceCondition:
    customFunction:
      functionName: check_won_status_code_product_picked
      functionArgs: [ field: current_payload ]
  modelMapping:
    segmentListMapping:
      - targetSegment: payload
        segmentListVariableMapping:
          - variableName: input_payload
            variableValue: current_payload
          - variableName: statusCode
            variableValue: global_variable.input_payload.event.warehousingOutboundNotification.shipment.warehousingOutboundStatusCode

          - variableName: TMShipmentId
            operation:
              - customFunction:
                  functionName: get_tms_shipment_ids
                  fields: [ field: global_variable.input_payload.event.warehousingOutboundNotification.shipment.transactionalReference ]

          - variableName: WON_ShippingLocationCode
            variableValue: global_variable.input_payload.event.warehousingOutboundNotification.shipment.shipFrom.primaryId

          - variableName: transportLoadId
            variableValue: global_variable.input_payload.event.warehousingOutboundNotification.shipment.shipmentTransportationInformation.transportLoadId

          - variableName: validate_ids
            operation:
              - customFunction:
                  functionName: tms_validate_won_ids
                  fields: [ field: global_variable.WON_ShippingLocationCode, field: global_variable.transportLoadId ]

          - variableName: vars_containers
            operation:
              - customFunction:
                  functionName: extract_variable_containers
                  fields: [ field: global_variable.input_payload.enrichment.shipment,
                            field: global_variable.TMShipmentId
                  ]

          - variableName: shipment_container
            operation:
              - customFunction:
                  functionName: form_shipment_container_document_without_transport_order
                  fields: [ field: global_variable.TMShipmentId,
                            field: global_variable.input_payload.enrichment.shipment,
                            field: global_variable.vars_containers,
                            field: global_variable.statusCode,
                            field: global_variable.input_payload.event.warehousingOutboundNotification.shipment,
                            property: "tms.uom.volume",
                            property: "tms.uom.weight"
                  ]
        sourceSegment: global_variable.shipment_container
        fieldMapping:
          - targetField: containerActionEnumVal
            default: "AT_UPDATE"
        segmentListMapping:
          - targetSegment: container
            sourceSegment: currentContainer
            condition:
              - customFunction:
                  functionName: validate_won_product_picked
                  fields: [field: global_variable.validate_ids,
                           field: global_variable.vars_containers,
                           field: global_variable.shipment_container.currentContainer
                  ]

            fieldMapping:
              - targetField: id
                sourceField: id
              - targetField: itemNumber
                sourceField: itemNumber
              - targetField: nestingValue
                sourceField: nestingValue
              - targetField: ratingUnitEnumDescr
                sourceField: ratingUnitEnumDescr
              - targetField: loadConfiguratorContainerTypeEnumDescr
                sourceField: loadConfiguratorContainerTypeEnumDescr
              - targetField: shipmentContainerCrossReference
                sourceField: shipmentContainerCrossReference
              - targetField: carrierPackageRegion
                sourceField: carrierPackageRegion
              - targetField: ratingUnitEnumDescr
                sourceField: ratingUnitEnumDescr
              - targetField: weightByFreightClassCount
                sourceField: weightByFreightClassCount
              - targetField: splitMethodEnumVal
                sourceField: splitMethodEnumVal
              - targetField: itemDescription
                sourceField: itemDescription
              - targetField: itemPackagingCommittedFlag
                sourceField: itemPackagingCommittedFlag
              - targetField: markedForLocationEnumVal
                sourceField: markedForLocationEnumVal
              - targetField: systemContainerTypeID
                sourceField: systemContainerTypeID
              - targetField: containerTypeCode
                sourceField: containerTypeCode
              - targetField: palletTypeCode
                sourceField: palletTypeCode
              - targetField: height
                sourceField: height
              - targetField: containerDescription
                sourceField: containerDescription
              - targetField: maximumScaledWeight
                sourceField: maximumScaledWeight
              - targetField: nestingDimensionEnumDescr
                sourceField: nestingDimensionEnumDescr
              - targetField: ignoreReferenceNumbersFlag
                sourceField: ignoreReferenceNumbersFlag
              - targetField: priority
                sourceField: priority
              - targetField: is3DLoadingRequiredFlag
                sourceField: is3DLoadingRequiredFlag
              - targetField: nestingDimensionEnumVal
                sourceField: nestingDimensionEnumVal
              - targetField: itemPackageLevelIDCode
                sourceField: itemPackageLevelIDCode
              - targetField: shipmentContainerNumber
                sourceField: shipmentContainerNumber
              - targetField: itemTypeDescr
                sourceField: itemTypeDescr
              - targetField: ignoreShipmentItemsFlag
                sourceField: ignoreShipmentItemsFlag
              - targetField: inputSourceEnumVal
                sourceField: inputSourceEnumVal
              - targetField: contentLevelTypeCode
                sourceField: contentLevelTypeCode
              - targetField: stackingRuleEnumVal
                sourceField: stackingRuleEnumVal
              - targetField: itemType
                sourceField: itemType
              - targetField: systemContainerID
                sourceField: systemContainerID
              - targetField: systemTransportOrderID
                sourceField: systemTransportOrderID
              - targetField: carrierPackageType
                sourceField: carrierPackageType
              - targetField: displayName
                sourceField: displayName
              - targetField: markedForLocationCode
                sourceField: markedForLocationCode
              - targetField: carrierPackageTypeDescr
                sourceField: carrierPackageTypeDescr
              - targetField: ratingUnitEnumVal
                sourceField: ratingUnitEnumVal
              - targetField: inputSourceEnumDescr
                sourceField: inputSourceEnumDescr
              - targetField: stackFactor
                sourceField: stackFactor
              - targetField: weightByFreightClassCode
                sourceField: weightByFreightClassCode
              - targetField: occurence
                sourceField: occurence
              - targetField: containerOrientationStr
                sourceField: containerOrientationStr
              - targetField: originCountryCode
                sourceField: originCountryCode
              - targetField: containerGLCategory
                sourceField: containerGLCategory
              - targetField: stackGroup
                sourceField: stackGroup
              - targetField: maximumNestingSize
                sourceField: maximumNestingSize
              - targetField: ignoreContainerOrientationsFlag
                sourceField: ignoreContainerOrientationsFlag
              - targetField: stackCode
                sourceField: stackCode
              - targetField: contentLevelTypeCodeDescr
                sourceField: contentLevelTypeCodeDescr
              - targetField: numberOfAttachments
                sourceField: numberOfAttachments
              - targetField: length
                sourceField: length
              - targetField: systemShipmentID
                sourceField: systemShipmentID
              - targetField: itemPackageLevelIDCodeDescr
                sourceField: itemPackageLevelIDCodeDescr
              - targetField: splitMethodEnumDescr
                sourceField: splitMethodEnumDescr
              - targetField: ignoreWeightByFreightClassFlag
                sourceField: ignoreWeightByFreightClassFlag
              - targetField: numberOfUnits
                sourceField: numberOfUnits
              - targetField: loadConfiguratorContainerTypeEnumVal
                sourceField: loadConfiguratorContainerTypeEnumVal
              - targetField: markedForLocationEnumDescr
                sourceField: markedForLocationEnumDescr
              - targetField: width
                sourceField: width
              - targetField: displayColor
                sourceField: displayColor
              - targetField: itemGroupCode
                sourceField: itemGroupCode
              - targetField: stackingRuleEnumDescr
                sourceField: stackingRuleEnumDescr
              - targetField: quantity
                sourceField: inputQty

            segmentMapping:
              - targetSegment: containerShippingInformation
                fieldMapping:
                  - targetField: scaledWeight
                    sourceField: containerShippingInformation.scaledWeight
                  - targetField: orderValue
                    sourceField: containerShippingInformation.orderValue
                  - targetField: declaredValue
                    sourceField: containerShippingInformation.declaredValue
                  - targetField: tareWeight
                    sourceField: containerShippingInformation.tareWeight
                  - targetField: pieces
                    sourceField: containerShippingInformation.pieces
                  - targetField: skids
                    sourceField: containerShippingInformation.skids
                  - targetField: ladenLength
                    sourceField: containerShippingInformation.ladenLength
                  - targetField: volume
                    sourceField: containerUnitVolume
                  - targetField: nominalWeight
                    sourceField: inputUnitWeight

            segmentListMapping:
              - targetSegment: weightByFreightClass
                sourceSegment: weightByFreightClass
                fieldMapping:
                  - targetField: freightClassCode
                    sourceField: freightClassCode
                  - targetField: freightClassNominalWeight
                    sourceField: freightClassNominalWeight

              - targetSegment: containerOrientation
                sourceSegment: containerOrientation
                fieldMapping:
                  - targetField: orientationAllowedEnumVal
                    sourceField: orientationAllowedEnumVal
                  - targetField: preference
                    sourceField: preference
                  - targetField: containerOrientationEnumVal
                    sourceField: containerOrientationEnumVal

              - targetSegment: referenceNumberStructure
                sourceSegment: referenceNumberStructure
                fieldMapping:
                  - targetField: item
                    sourceField: item
                  - targetField: referenceNumberTypeCodeDescr
                    sourceField: referenceNumberTypeCodeDescr
                  - targetField: referenceNumber
                    sourceField: referenceNumber
                  - targetField: id
                    sourceField: id
                  - targetField: referenceNumberTypeCode
                    sourceField: referenceNumberTypeCode

              - targetSegment: shipmentItem
                sourceSegment: shipmentItem
                fieldMapping:
                  - targetField: inputSourceEnumVal
                    sourceField: inputSourceEnumVal
                  - targetField: itemNumber
                    sourceField: itemNumber
                  - targetField: systemContainerID
                    sourceField: systemContainerID
                  - targetField: shipmentItemCrossReference
                    sourceField: shipmentItemCrossReference
                  - targetField: shipmentItemFreightClassCode
                    sourceField: shipmentItemFreightClassCode
                  - targetField: extendedItemOrderValue
                    sourceField: extendedItemOrderValue
                  - targetField: inputSourceEnumDescr
                    sourceField: inputSourceEnumDescr
                  - targetField: harmonizedTariffCode
                    sourceField: harmonizedTariffCode
                  - targetField: originCountryCode
                    sourceField: originCountryCode
                  - targetField: NMFCCode
                    sourceField: NMFCCode
                  - targetField: extendedItemDeclaredValue
                    sourceField: extendedItemDeclaredValue
                  - targetField: nominalWeight
                    sourceField: nominalWeight
                  - targetField: id
                    sourceField: id
                  - targetField: itemDescription
                    sourceField: itemDescription
                  - targetField: itemOrderValue
                    sourceField: itemOrderValue
                  - targetField: extendedNominalWeight
                    sourceField: extendedNominalWeight
                  - targetField: serialLotControlEnumDescr
                    sourceField: serialLotControlEnumDescr
                  - targetField: proratedScaledWeight
                    sourceField: proratedScaledWeight
                  - targetField: itemQuantity
                    sourceField: itemQuantity
                  - targetField: itemDeclaredValue
                    sourceField: itemDeclaredValue
                  - targetField: ignoreReferenceNumbersFlag
                    sourceField: ignoreReferenceNumbersFlag
                  - targetField: serialLotNumbers
                    sourceField: serialLotNumbers
                  - targetField: serialLotControlEnumVal
                    sourceField: serialLotControlEnumVal
                  - targetField: shipmentItemNumber
                    sourceField: shipmentItemNumber
                  - targetField: systemShipmentItemID
                    sourceField: systemShipmentItemID
                segmentListMapping:
                  - targetSegment: referenceNumberStructure
                    sourceSegment: referenceNumberStructure
                    fieldMapping:
                      - targetField: referenceNumberTypeCodeDescr
                        sourceField: referenceNumberTypeCodeDescr
                      - targetField: systemReferenceNumberID
                        sourceField: systemReferenceNumberID
                      - targetField: referenceNumber
                        sourceField: referenceNumber
                      - targetField: createdDateTime
                        sourceField: createdDateTime
                      - targetField: id
                        sourceField: id
                      - targetField: referenceNumberTypeCode
                        sourceField: referenceNumberTypeCode
                      - targetField: updatedDateTime
                        sourceField: updatedDateTime






