---
- sourceModel: warehousingOutboundNotification
  targetModel: process_reference_number_update
  sourceCondition:
    customFunction:
      functionName: check_won_status_Code
      functionArgs: [ field: current_payload ]
  modelMapping:
    segmentMapping:
      - targetSegment: payload
        # variables
        fieldVariableMapping:
          - variableName: input_payload
            variableValue: current_payload
          - variableName: WON_ShippingLocationCode
            variableValue: global_variable.input_payload.event.warehousingOutboundNotification.shipment.shipFrom.primaryId
          - variableName: transportLoadId
            variableValue: global_variable.input_payload.event.warehousingOutboundNotification.shipment.shipmentTransportationInformation.transportLoadId

          - variableName: TMShipmentId
            operation:
              - customFunction:
                  functionName: get_tms_shipment_ids
                  fields: [ field: global_variable.input_payload.event.warehousingOutboundNotification.shipment.transactionalReference ]

          - variableName: validate_ids
            operation:
              - customFunction:
                  functionName: tms_validate_won_ids
                  fields: [ field: global_variable.WON_ShippingLocationCode, field: global_variable.transportLoadId ]

          - variableName: countOfUnWavedShipmentsAtStop
            operation:
              - customFunction:
                  functionName: get_count_of_unwaved_shipments_at_stop
                  fields: [ field: global_variable.input_payload.enrichment.load.shipmentLeg.shipFromLocationCode,
                            field: global_variable.input_payload.event.warehousingOutboundNotification.shipment.shipFrom.additionalPartyId.value
                  ]

          - variableName: reference_number_shipment_leg
            operation:
              - customFunction:
                  functionName: update_shipment_ref_based_on_enriched_shipment_leg
                  fields: [ field: global_variable.input_payload.event.warehousingOutboundNotification.shipment,
                      field: global_variable.input_payload.enrichment.shipment,
                      field: global_variable.input_payload.event.warehousingOutboundNotification.shipment.warehousingOutboundStatusCode,
                      field: global_variable.TMShipmentId,
                      property: "tms.defaults.shipmentStatus.stockAllocated",
                      property: "tms.defaults.shipmentStatus.productPicked",
                      property: "tms.refNumActionEnumVal.update"
                  ]

          - variableName: reference_number_shipment
            operation:
              - customFunction:
                  functionName: update_shipment_ref_based_on_enriched_shipment
                  fields: [ field: global_variable.input_payload.event.warehousingOutboundNotification.shipment,
                            field: global_variable.input_payload.enrichment.shipment,
                            field: global_variable.input_payload.event.warehousingOutboundNotification.shipment.warehousingOutboundStatusCode,
                            field: global_variable.TMShipmentId,
                            property: "tms.defaults.shipmentStatus.stockAllocated",
                            property: "tms.defaults.shipmentStatus.productPicked",
                            property: "tms.defaults.shipmentStatus.waveCancelled",
                            property: "tms.refNumActionEnumVal.update"
                  ]

          - variableName: reference_number_load
            operation:
              - customFunction:
                  functionName: update_shipment_ref_based_on_enriched_merged_load
                  fields: [ field: global_variable.countOfUnWavedShipmentsAtStop,
                            field: global_variable.input_payload.enrichment.load,
                            field: global_variable.input_payload.event.warehousingOutboundNotification.shipment,
                            field: global_variable.WON_ShippingLocationCode,
                            field: global_variable.TMShipmentId,
                            property: "tms.defaults.shipmentStatus.stockAllocated",
                            property: "tms.defaults.shipmentStatus.productPicked",
                            property: "tms.refNumActionEnumVal.update",
                            property: "tms.defaults.stopStatus.loadWave"
                  ]

          - variableName: reference_number_stop
            operation:
              - customFunction:
                  functionName: update_shipment_ref_based_on_enriched_merged_stop
                  fields: [ field: global_variable.input_payload.enrichment.load,
                            field: global_variable.input_payload.event.warehousingOutboundNotification.shipment,
                            field: global_variable.WON_ShippingLocationCode,
                            field: global_variable.TMShipmentId,
                            property: "tms.defaults.shipmentStatus.stockAllocated",
                            property: "tms.defaults.shipmentStatus.productPicked",
                            property: "tms.refNumActionEnumVal.update",
                            property: "tms.defaults.stopStatus.loadWave"
                  ]
        segmentListMapping:
          - targetSegment: referenceNumberUpdateData
            sourceSegment: global_variable.reference_number_shipment_leg
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: 'WM_SHIPMENT'
              - targetField: referenceNumberEntityKey
                sourceField: shipment_leg_mapped_data.reference_number_entity_key
              - targetField: referenceNumberCategoryEnumVal
                default: 'RNC_SHPM'
              - targetField: systemReferenceNumberID
                sourceField: shipment_leg_mapped_data.system_reference_number_id
              - targetField: referenceNumber
                sourceField: shipment_leg_mapped_data.reference_number
              - targetField: referenceNumberActionEnumVal
                sourceField: shipment_leg_mapped_data.reference_number_action_enum_val

          - targetSegment: referenceNumberUpdateData
            sourceSegment: global_variable.reference_number_shipment
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: 'WM_SHIPMENT'
              - targetField: referenceNumberEntityKey
                sourceField: mapped_data.reference_number_entity_key
              - targetField: referenceNumberCategoryEnumVal
                default: 'RNC_SHPM'
              - targetField: systemReferenceNumberID
                sourceField: mapped_data.system_reference_number_id
              - targetField: referenceNumber
                sourceField: mapped_data.reference_number
              - targetField: referenceNumberActionEnumVal
                sourceField: mapped_data.reference_number_action_enum_val

          - targetSegment: referenceNumberUpdateData
            sourceSegment: global_variable.reference_number_load
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: "WM_WH_STS_"
              - targetField: referenceNumberEntityKey
                sourceField: load_mapped_data.reference_number_entity_key
              - targetField: referenceNumberCategoryEnumVal
                default: "RNC_LD_LEG"
              - targetField: referenceNumber
                sourceField: load_mapped_data.reference_number
              - targetField: referenceNumberActionEnumVal
                sourceField: load_mapped_data.reference_number_action_enum_val
              - targetField: systemReferenceNumberID
                sourceField: load_mapped_data.system_reference_number_id

          - targetSegment: referenceNumberUpdateData
            sourceSegment: global_variable.reference_number_stop
            fieldMapping:
              - targetField: referenceNumberTypeCode
                default: "WM_SHP_STS"
              - targetField: referenceNumberEntityKey
                sourceField: stop_mapped_data.reference_number_entity_key
              - targetField: referenceNumberCategoryEnumVal
                default: "RNC_STOP"
              - targetField: referenceNumber
                sourceField: stop_mapped_data.reference_number
              - targetField: referenceNumberActionEnumVal
                sourceField: stop_mapped_data.reference_number_action_enum_val
              - targetField: systemReferenceNumberID
                sourceField: stop_mapped_data.system_reference_number_id
